CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id` VARCHAR(50) NOT NULL,
  `action` VARCHAR(50) NOT NULL,
  `entityType` VARCHAR(30) NOT NULL,
  `entityId` VARCHAR(50) NULL,
  `userId` VARCHAR(50) NULL,
  `userName` VARCHAR(255) NULL,
  `details` TEXT NULL,
  `metadata` JSON NULL,
  `severity` VARCHAR(10) NOT NULL DEFAULT 'INFO',
  `ipAddress` VARCHAR(45) NULL,
  `userAgent` VARCHAR(500) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `audit_logs_action_idx` (`action`),
  INDEX `audit_logs_entityType_idx` (`entityType`),
  INDEX `audit_logs_userId_idx` (`userId`),
  INDEX `audit_logs_severity_idx` (`severity`),
  INDEX `audit_logs_createdAt_idx` (`createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
